### PR TITLE
Add az_ulib_c and create a small device manager at az_ulib_dm.

### PR DESCRIPTION
**Pull request by mamokarz**

### CODE REVIEW

**Comment by mamokarz** [comment]
@smcd253 is added to the review. #Closed

**Comment by mamokarz** [comment]
@cindydeng1998 is added to the review. #Closed

**Review by smcd253 — APPROVED** [review]
LGTM! It's finally coming together!

**Comment by mamokarz** [comment]
:)

---
In reply to: [627109620](https://github.com/mamokarz/getting-started/pull/1#issuecomment-627109620) [](ancestors = 627109620)

**Pull request merged**
